class Vt100Codes(object):
  def __init__(self):
    self.reset = '\x1b[0m'
    self.bold = '\x1b[1m'
    self.dim = '\x1b[2m'
    self.under = '\x1b[4m'
    self.reverse = '\x1b[7m'
    self.hide = '\x1b[8m'
    self.clearscreen = '\x1b[2Jm'
    self.clearline = '\x1b[2K'
    self.black = '\x1b[30m'
    self.red = '\x1b[31m'
    self.green = '\x1b[32m'
    self.yellow = '\x1b[33m'
    self.blue = '\x1b[34m'
    self.magenta = '\x1b[35m'
    self.cyan = '\x1b[36m'
    self.white = '\x1b[37m'
    self.bg_black = '\x1b[40m'
    self.bg_red = '\x1b[41m'
    self.bg_green = '\x1b[42m'
    self.bg_yellow = '\x1b[43m'
    self.bg_blue = '\x1b[44m'
    self.bg_magenta = '\x1b[45m'
    self.bg_cyan = '\x1b[46m'
    self.bg_white = '\x1b[47m'
    self.newline = '\r\n' + self.reset